import "./globals.css";
import Navbar from "@/app/_components/navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="text-current">
        {/*<Navbar/>*/}
        {children}
        </body>
        </html>
    );
}
